### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'moments'

### ISSUE THREAD

**Issue by waleedka** [titu1994/BatchRenormalization#2]
Looks like the code was updated to expect K.moments() to be available, but it's not part of the Keras backend module (I'm using Keras 2.0.5). I'm guessing this code is not maintained anymore and that I should use the version in keras-contrib, right?

**Comment by xdvx** [comment]
Same error here.

Edit, I've found that keras tensorflow backend was missing this piece of code:

```
def moments(x, axes, shift=None, keep_dims=False):
    ''' Wrapper over tensorflow backend call '''

    return tf.nn.moments(x, axes, shift=shift, keep_dims=keep_dims)
```

**Comment by titu1994** [comment]
@waleedka @xdvx Sorry about that. I was on vacation and forgot to read my mails.

I merged the code from Keras Contrib with this repo and didn't realize that the moments function from Keras Contrib would not work here (since moments doesnt exist in core keras, only in contrib).

A simple method to check the backend, import the appropriate backend engine and then perform the update will be sufficient here. 

Sorry, and thanks for bringing this to my attention.

**Comment by Athaagra** [comment]
AttributeError: module 'keras.backend' has no attribute 'slice'.
I am trying to train Bi-Lstm with CRF on top and i am getting this error Keras version=2.1.4
